### ISSUE TITLE
Collator locale falls to 'root' in deployed server

### ISSUE THREAD

**Issue by Shan3103** [erickguan/ffi-icu#66]
Collator locale falls to 'root' in cloud deployed application server but works fine while testing in localhost. We are trying to compare and sort based on Swedish locale. Collator.locale is 'sv' in localhost but 'root' in deployed server. 

We are not able to debug further in code and there are no errors. Could you please let us know in what situation the locale will be set to root or if this is dependant on any configuration?

**Comment by Shan3103** [comment]
@erickguan Could you please help with this query?

**Comment by erickguan** [comment]
Hey, assuming you passed `sv` to collator, this is what happens for icu. Did you check your collator's locale and the value you passed to the initializer? The module method is simply a proxy to the temporary collator.

For specific:

> The locale containing the required collation rules. Special values for locales can be passed in - if NULL is passed for the locale, the default locale collation rules will be used. If empty string ("") or "root" are passed, the root collator will be returned

https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/ucol_8h.html#a3b0bf34733dc208040e4157b0fe5fcd6

This is unlikely. There is a possibility that your icu library doesn't have the right data. But your debugging needs to start from  the cloud where your problem is.

**Comment by erickguan** [comment]
It's good that you are passing the locale correctly. Now you should continue with the more difficult part of debugging. You are your system's owner.
One hint is `$DEBUG`, `$VERBOSE` can be used to print error code when you initialize a collator. See `Lib.check_error`.
For collator's fallback behavior, I recommend you read icu's code. Besides data loading, it should be quite straightforward.
